# add the following to _config.yml file
title: Ray CHOW-TOUN
logo: /assets/img/Ray.LinkedIn.10.2021.BW.200.Circle.png
theme: jekyll-theme-minimal
# github:
#  is_project_page: false
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Swiss based Project Manager and Product Owner with Identity Authentication background 
  <br><br>
  <a href="https://www.linkedin.com/in/raychow2004/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
  <br><br>
  
