# add the following to _config.yml file
title: Ray CHOW-TOUN
logo: /assets/img/Ray.LinkedIn.10.2021.BW.200.Circle.png
theme: jekyll-theme-minimal
# github:
#  is_project_page: false
<a href="https://www.linkedin.com/in/raychow2004/">👔 LinkedIn</a>
  
